name: Update Sheet Manually
on: workflow_dispatch

env:
  CYPRESS_LAMBDA_API_URL: ${{ secrets.CYPRESS_LAMBDA_API_URL }}
  CYPRESS_S3_BUCKET_URL: ${{ secrets.CYPRESS_S3_BUCKET_URL }}

jobs:
  create-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
      - name: yarn fixture
        run: |
          yarn fixture
      - uses: actions/upload-artifact@main
        with:
          name: fixtures
          path: cypress/fixtures
      - uses: actions/upload-artifact@main
        with:
          name: specs
          path: cypress/integration

  cypress-run:
    runs-on: ubuntu-latest
    needs: create-fixtures
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/download-artifact@main
        with:
          name: fixtures
          path: cypress/fixtures
      - uses: actions/download-artifact@main
        with:
          name: specs
          path: cypress/integration
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 120
        with:
          record: true
          parallel: true
          group: 'Update sheet'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
