name: Update Sheet Manually
on:
  workflow_dispatch:
  repository_dispatch:

env:
  CYPRESS_LAMBDA_API_URL: ${{ secrets.CYPRESS_LAMBDA_API_URL }}
  CYPRESS_S3_BUCKET_URL: ${{ secrets.CYPRESS_S3_BUCKET_URL }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: yarn install
        run: |
          yarn install --immutable --immutable-cache
      - name: yarn fixture
        run: |
          yarn fixture
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 60
        with:
          install: false
          record: false
          start: yarn start
          wait-on: 'http://localhost:3000'
          # wait for 600 seconds for the server to respond
          wait-on-timeout: 600
          browser: chrome
          headless: true
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
